# permissions for end users to view identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: identity
    app.kubernetes.io/managed-by: kustomize
  name: identity-viewer-role
rules:
- apiGroups:
  - idp.zx.io
  resources:
  - identities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - idp.zx.io
  resources:
  - identities/status
  verbs:
  - get
