apiVersion: idp.zx.io/v1
kind: Identity
metadata:
  labels:
    app.kubernetes.io/name: identity
    app.kubernetes.io/managed-by: kustomize
  name: identity-sample
spec:
  # TODO(user): Add fields here
